name: Publish to Dockerhub

on:
  push:
    branches:
      - master
      - 'releases/**'

  release:
    types: [published]

jobs:
  push_to_registry:
    if: github.repository == 'NKI-GCF/gensum'
    name: Push Docker image to Docker Hub / GitHub Docker Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push dev image
        uses: docker/build-push-action@v2
        if: github.event_name == 'push'
        with:
          push: true
          tags: |
            nkigcf/gensum:dev
            ghcr.io/nki-gcf/gensum:dev

      - name: Push release image
        uses: docker/build-push-action@v2
        if: github.event_name == 'release'
        with:
          push: true
          tags: |
            nkigcf/gensum:${{ github.event.release.tag_name }}
            nkigcf/gensum:latest
            ghcr.io/nki-gcf/gensum:${{ github.event.release.tag_name }}
            ghcr.io/nki-gcf/gensum:latest
